### ISSUE TITLE
Item of Components instead of Segment of Items?

### ISSUE THREAD

**Issue by ormsbee** [openedx/openedx-learning#18]
@bradenmacdonald, @jmakowski1123, and I recently had a conversation where we were going over terminology for the various entities we have in our system and how to reconcile that with existing conventions.

## Item vs. Component

The current state of Learning Core's terminology is in [ADR 0002](https://github.com/openedx/openedx-learning/blob/8bf74651748b5ec7b893cddb50afe8630588195a/docs/decisions/0002-content-flexibility.rst).

I had up until this point used "Item" as the layer that would map to a single XBlock (like VideoBlock, ProblemBlock, etc.). I did this because "block" was an overloaded term in our system, and other standards like QTI use the term Item in a roughly analogous way.  @jmakowski1123 brought up the very valid point that these things are known as Components in the Studio UI and all the documentation.

We broadly agreed that either term would probably be okay, and that we should favor the one that users are already familiar with (i.e. Component).

## Segments vs. ItemPairs

In the same meeting, @bradenmacdonald brought up that Segments are primarily used for simple pairs of HTML content introduction + a problem, and suggested a name that reflected that, like ItemPair.

Later that day, @feanil and I paired on making [a data model for Segments](https://github.com/ormsbee/openedx-learning/pull/1). @feanil brought up the idea that perhaps we didn't need a composition system like Segments if XBlock could be extended to allow for arbitrary HTML to be prepended to existing blocks.

In a followup conversation @JAAkana mentioned that there are a few known scenarios where we want Segment-like functionality:

* HTML + problem is the most common
* Video + Problem is also a known grouping
* Video + HTML is a "rare-but-neat" example, where videos are followed by supplemental links/controls/context in a text block.

This supports the idea that we should aim for something more general.

## An Item of Components?

**Proposal: What we've been calling "Item" so far would become "Component" and what we've been calling "Segment" would become "Item".**

Advantages:

* This maps to existing language and expectation that Component = one XBlock, like a Problem.
* "Item" feels like a natural way to talk about a thing that is conceptually one thing from the student's point of view.
* This still feels like it could be aligned with IMS terminology (for content where Component and Item are 1:1).

Conceptually, we're saying that Item is a coherent piece for the purposes of display and sharing. Components are a lower-level concept that delegates how to render things and store student state.

Also tagging @jristau1984, @kdmccormick, @pdpinch

---

What do folks think?

**Comment by ormsbee** [comment]
BTW, one aspect of splitting the idea of Item and Component (whatever we call them) that's really appealing to me is that it means we have a logical place to hang nice URL slugs that are independent of the corresponding XBlock. A Component might need an `identifier` that is some part of usage key, but an Item is independent of that. So you could just call it "intro_to_puppies" or something short and sweet.

**Comment by bradenmacdonald** [comment]
@ormsbee Is it the case that every Component is always part of an Item, then? (but often 1:1) If so, I like your proposal. I do suspect that if we aren't careful it could be confusing for users, or the terms Item and Component may start to be used interchangeably though.

**Comment by ormsbee** [comment]
> @ormsbee Is it the case that every Component is always part of an Item, then? (but often 1:1) If so, I like your proposal.

Yup!

> I do suspect that if we aren't careful it could be confusing for users, or the terms Item and Component may start to be used interchangeably though.

Agreed. I also think there's going to have to be a bit of delicacy around what things apply to which, e.g. titles, grading, etc. Also, whether Item can be abused to the point where it's another Unit. We might want to clamp down early on some of the capabilities (e.g. force it to be at max three components, etc.) I feel fuzzy on the specifics of where we draw the lines on all of those things, but I do feel generally good about decoupling "this is one thing to the student" vs. "these 2-3 things in terms of user state and plugin used for rendering".

**Comment by feanil** [comment]
Thanks for the follow up @ormsbee .  Given what you found, yea, it makes sense to me that having a generic grouper of low level components.  The name change also makes sense.

**Comment by kdmccormick** [comment]
@ormsbee

Renaming Item to Component makes perfect sense to me 👍🏻 

In terms of renaming Segment to Item: Do you think "Item" is the term that will be presented to users for this concept? If so, go for it--I'm all about aligning our technical and product language when possible. However, if you suspect that "Item" will just be the technical name and end users will see a different word, then I would favor something choosing a less generic, like "Assembly", "Parcel", or just "Segment". Just like with "Object", I worry that it will be easy to mix up our meaning of "Item" with the meanings in other contexts like Python, Mongo, English, etc.

**Comment by jmakowski1123** [comment]
> > In terms of renaming Segment to Item: Do you think "Item" is the term that will be presented to users for this concept?
> 
> @jmakowski1123 and @JAAkana probably have thoughts here, but I would advocate for using Item when talking about this to users.

@ormsbee My only concern with using "item" when presenting this flow to users (particularly course authors and instructional designers) is that "component" and "item" can effectively mean the same thing in every day language, so the nuance/specificity we are attaching here to "item" has a danger of being confused from an end-user PoV. From a learner PoV, I think it matters less - they will see and interact with the content within the item intuitively and have no need to dive into the taxonomy layers beneath it. I agree with @kdmccormick , it'd be ideal to align product and tech naming conventions wherever possible. Is there a synonym we could use for "item" that conveys "component+component that are presented to the learner as a single entity?" Block was the first word that came to my mind but that's a can of worms we don't want to touch.

**Comment by kdmccormick** [comment]
> Is there a synonym we could use for "item" that conveys "component+component that are presented to the learner as a single entity?

Hmm, I didn't imagine that learners would know when two Components were part of Item. I imagined that content authors--particularly ones that are reusing/randomizing content--would be the only ones aware of Item associations. I could be totally off here, though.

**Comment by jmakowski1123** [comment]
> > Is there a synonym we could use for "item" that conveys "component+component that are presented to the learner as a single entity?
> 
> Hmm, I didn't imagine that learners would know when two Components were part of Item. I imagined that content authors--particularly ones that are reusing/randomizing content--would be the only ones aware of Item associations. I could be totally off here, though.

Agree, the learner persona would not be presented the underlying taxonomies. I was thinking from the PoV of the course author/instructional designer and asking what term we could present to them that would translate well into "component+component that are presented to the [your] learner as a single entity". I see now where that sentence could be interpreted differently than I intended it!

**Comment by ormsbee** [comment]
> Actually, what about "entity"?

I think Entity could work, but I prefer Item because of its use in other standards like QTI. Also, I think Item more naturally conveys an individual piece of content when we want more specific modifiers. For example, to me, `AssessmentItem` is clearly a piece of content that is used in an Assessment, whereas `AssessmentEntity` could be some external service that _does_ Assessment.

What if we frame it in a much more constrained way within the UI? The underlying framework might be able to string any two or three Components into an Item, but the UI can present it as "Introduction + Problem" or "Video + Problem" as pre-canned Item types. Most course teams have a handful of patterns that consistently repeat. Why not make them into first class entities in the system? @JAAkana: Are there currently internal names for these patterns?

Items then become more than two or three Components strung together. Items become opinionated tools for organizing content. Really advanced users could make their own arbitrary Item types that are combinations of different types of Components, but most would choose from the standard gallery.

Something that's really interesting to me about this framing of Item is that takes a big bite into edx-platform's concept of a Unit and nibbles a bit at its use case for a Sequence. Most Units these days are either a bit of static text, a problem (+ optional intro text), or a video (+ optional intro text). This would often be a single Item in this framing.

Sometimes an entire Sequence is just used to have one Unit act as a Video and the next Unit hold one Problem. This would also be an Item (possibly with different presentation styles).

We'd still need to have a data representation of an edx-platform-style Unit and Sequence of Units somewhere. Backwards compatibility means that we have to support having 60 named problems in a single Unit, and the way that library content into courses requires some Unit concept. But those concepts don't have to extend down to the Learning Core.

Also, I realize that I still haven't addressed the original concern about confusing the Component vs. Item terminology. I'm not sure how to make that clearer while still keeping the Component terminology. For instance, Item>ItemPart or Molecule>Atom are both clearer, but don't preserve the existing term. I think that if someone hears Item and Component, they'd assume Item>Component, which is what we want.

The only other terms I can think of to go on top of Component all seem kinda clunky. Cluster sounds too big, and System is way, way too big. Section is both too big and has overlap with Section/Subsection terminology. Element is too small. I think Entity is better than all of these, but I still prefer Item for the reasons I originally stated.

Words are hard. 😞

**Comment by ormsbee** [comment]
Possibly controversial way to differentiate between a Unit and an Item: say Components don't have titles. Only Items have titles. Much of the time, the titles for the small pieces that would be Components are useless anyway. We have people making a title for the Unit, a blank title for the HTML introducing a problem, and then the default title (like "Multiple Choice") for the problem in the Unit.

**Comment by jmakowski1123** [comment]
> 
> Also, I realize that I still haven't addressed the original concern about confusing the Component vs. Item terminology. I'm not sure how to make that clearer while still keeping the Component terminology. For instance, Item>ItemPart or Molecule>Atom are both clearer, but don't preserve the existing term. I think that if someone hears Item and Component, they'd assume Item>Component, which is what we want.
> 
> The only other terms I can think of to go on top of Component all seem kinda clunky. Cluster sounds too big, and System is way, way too big. Section is both too big and has overlap with Section/Subsection terminology. Element is too small. I think Entity is better than all of these, but I still prefer Item for the reasons I originally stated.
> 
> Words are hard. 😞

It might be helpful to present the semantic challenge to a few users and see if it results in a lot/some/no confusion. I'd like to bring it up to the folks at MRI, Harvard and WGU in the next 3-5 days if that sounds ok? At least we'll have a clearer data point about how it presents to users. And from a UI perspective, I like the idea of guiding authors toward templated Items. It could be that that solves, or at least gets ahead of, much potential confusion.

**Comment by jmakowski1123** [comment]
> Possibly controversial way to differentiate between a Unit and an Item: say Components don't have titles. Only Items have titles. Much of the time, the titles for the small pieces that would be Components are useless anyway. We have people making a title for the Unit, a blank title for the HTML introducing a problem, and then the default title (like "Multiple Choice") for the problem in the Unit.

What would it look like in the context of building content libraries, for components not to have titles? For example, if a user is building a library of just videos, what would it means for those video components to not have titles?

**Comment by ormsbee** [comment]
> It might be helpful to present the semantic challenge to a few users and see if it results in a lot/some/no confusion. I'd like to bring it up to the folks at MRI, Harvard and WGU in the next 3-5 days if that sounds ok? 

Absolutely! Thank you!

> What would it look like in the context of building content libraries, for components not to have titles? For example, if a user is building a library of just videos, what would it means for those video components to not have titles?

Good point. My initial take on it was that the libraries would have Items, even if those Items have just a single Video Component in them. So from the user's point of view, they'd still have titles.

But I think I see what you're getting in terms of the complexity in borrowing scenarios:

* What if there are text intros with those videos? Would they always be connected to the Videos at the library level?
* Would the people importing Videos into their courses want to have their own introduction?
* Are the people providing the videos even able to write such introductions (e.g. if it's a dedicated video team that just records and uploads the content without having to understand it).
* Does that mean we need the ability to copy parts of an Item? So maybe the course has an Item that has a copy of the Library Item, but prepends it with its own intro text Component?

That's a can of worms. On the other hand, this sort of ability to do partial borrows and updates seems like a problem we actually want to solve in other areas (e.g. CCX), and breaking it up this way gives some method for separating parts that we might want to strictly track from the library (e.g. problems, videos) from parts we want to only update ourselves (intro text).

Going to try to think about this some more...

**Comment by kdmccormick** [comment]
Sorry to continue bikeshedding this @jmakowski1123 and @ormsbee , but during our meeting I couldn't help but think:

What if "Items" were just called "Units"?

We mentioned that the currently meaning of a Studio Unit would probably be captured as an Item in the current data model. If so, then this new definition of "Units" would be a superset of the existing definition.

A "Unit" generally means something that is indivisible, atomic, and/or a building block. Likewise, the thing we currently call "Item" is an indivisible chunk of learning, and is the smallest unit of reusable content in the system. Plus, "Modular Learning Units" makes a lot of sense to my ears.

Just some food for thought.

**Comment by ormsbee** [comment]
> What if "Items" were just called "Units"?
>
> We mentioned that the currently meaning of a Studio Unit would probably be captured as an Item in the current data model. If so, then this new definition of "Units" would be a superset of the existing definition.

This came up at some point in our discussions, but my concern was that it doesn't precisely line up to a Unit in Studio. It often does, but there are plenty of instances where a single Unit will have many things we would consider distinct Items in them. In some cases, what we'd think of as a single Item is spread across two adjacent Units.

I thought that we could keep the definition of an Item tighter and simpler if we didn't have to stretch it to allow for all the additional ways that a Unit could be authored in Studio. I also thought it would be easier to model the use case of a randomized library item being fitted into a Unit if those things were separate concepts (though I'm just starting to have second thoughts there, since it seems like we might want to do both Item and Component level borrowing).

**Comment by feanil** [comment]
> seems like we might want to do both Item and Component level borrowing

Can you elaborate on this? I thought one of the reasons to have both an Item and a Component is to have the Item be the canonical thing that gets reused and you can't just borrow Components.  Maybe I misunderstood?

**Comment by ormsbee** [comment]
> Can you elaborate on this? I thought one of the reasons to have both an Item and a Component is to have the Item be the canonical thing that gets reused and you can't just borrow Components. Maybe I misunderstood?

That was my original intention, but @jmakowski1123 and I talked about other scenarios as well, in particular in an interview with one of the folks we're discussing use cases with. The main issue with reuse only at the Item level is that component dependencies are not bi-directional. For instance, say you have a video explaining some concept, and a follow-up question that references the video directly ("In the video, you saw {x}..."). The question makes no sense outside the context of the video, but the video may be useful independently. You might add your own question to it.

Additionally, you might want to use an item with (intro text, video, question)  but alter just the introduction text. This is especially the case if the content is being bootstrapped from course content that isn't well structured to be agnostic about where it is in the structure of a course.

Hmmm... walking through all that, this really does start sounding like a Unit. I just don't want to have to stretch it to cover other Unit edge cases. Maybe the problem is that I've been thinking that this has to be able to plop into the middle of an existing edx-platform Unit. Maybe these can be a new type of Unit, so you would only add it in the UX at that layer, and we have to worry about fewer combinations. Actually, that might make it a lot simpler–we'd only have to attach some time level Unit metadata, and we could more completely and independently control the rendering pipeline...

**Comment by Lyla-Fischer** [comment]
Unit is going to be confusing to existing educators where it is the collection of learning resources that ends in an exam.
