### ISSUE TITLE
Learning Context vs. Learning Package

### ISSUE THREAD

**Issue by ormsbee** [openedx/openedx-learning#21]
@jmakowski1123 and I spoke about this today and I just wanted to jot it down before I forgot.

LearningContext is intended to be a generalization of Course, and is language that already exists in edx-platform. The idea is that Libraries, Courses, mini-courses, Pathways, etc. are all LearningContexts.

But it couples two important things:

1. The thing that is published/versioned at one time and authored by one group of people.
2. The thing we store student state against. The same problem in different LearningContexts have different user state.

We can sort of see a little of that in Libraries, which seem like an odd thing to store student state against. But by and large, it holds together for the large-to-mid-size chunks of content that exist today and the LabXchange example.

But does this relationship scale down towards the Modular Learning project use cases? Are there situations where we want a bunch of learning material, published by different teams at different cadences, to still add up to some unified learning context for the purposes of grading? If so, what are the boundaries of that?

**Comment by ormsbee** [comment]
Based on some offline discussions in front of a whiteboard, I'm currently going with @feanil's suggested terminology of Learning Package as the authored thing, and Learning Context as the collection of student state.

**Comment by jmakowski1123** [comment]
As I'm looking back through some of the raw user interview data, the idea of "learning products" pops up a few times. What if we considered learning product, rather than learning package? Learning product may translate more smoothly in terms of user-facing communications, marketing and branding - ie "Open edX enables you to deliver diverse and customizable learning products, ranging from full courses to short courses, micro learning pathways, credits, etc etc...."

**Comment by ormsbee** [comment]
In this scenario, would a Learning Product represent the published work of a single group of people (e.g. a course team), or the aggregation of potentially multiple published works by multiple groups of people that aggregate into a coherent learning experience for a student?

Or to reframe it–right now, all of a student's experience of our only existing in-platform Learning Product (the course) is ultimately controlled by a course team. There is content from Libraries, but they are selected by the Course team and are copied into the course at a specific version. Does that kind of relationship still exist in a more modular learning world? Is there always a single "Product" that is controlled by a single authoring entity, and the student experiences these separately (like different courses)?

Splitting Learning Context and Learning Package was an attempt to understand if we need to decouple the "content that is created by authors" from the "learning that is experienced by students". I'm honestly not sure if that's a useful distinction to make, because I'm still really fuzzy on the experience that knits together some of these potentially smaller learning pieces. But if that distinction is worth making, I'm not clear on which side of it that "Learning Product" falls on.

**Comment by ormsbee** [comment]
Follow-up from this conversation is that LearningProduct = the published pieces of content of various size, and LearningContext = the student experienced thing (which might be multiple products at some point).

**Comment by Lyla-Fischer** [comment]
How would a learning product relate to a blockstore's "bundle"?
