### ISSUE TITLE
Does LearningContextVersionItemVersion need to exist?

### ISSUE THREAD

**Issue by ormsbee** [openedx/openedx-learning#22]
The LearningContextVersionItemVersion model currently exists as a way to version the Items in the LearningContext as a whole. This is inefficient–a library with thousands of things in it will get thousands of rows updated for a single published change, because only a handful of Items may change from version to version. In the past, I've tried to find more efficient ways to represent the idea that "this Item exists across this range of versions". But now I'm beginning to think that, at least for the "library of items" use case, we don't need this model at all.

Courses currently track versions at the level of the entire course. The structure doc that represents a course in SplitModuleStore is an immutable document that gets created with each new version and the "active_versions" collection pointer to it gets changed with each publish. This serves a few purposes:

1. It makes sure that publishes are atomic. Old Mongo had a problem where courses would get partially uploaded when import failed part of the way through, leading to missing and broken content.
2. It gives an easy way to reconstruct and refer to a snapshot of the course as a whole at a certain point in time.
3. The fact that the course as a whole had a version gave other systems a chance to cache the data that they needed by the version. This was helpful to get around the slow data access patterns that the Modulestore supported. This was important because the content could be changed in non-obvious ways (e.g. by changing an inherited field in a container above the content).

I don't think those things are as relevant for the general use case in `itemstore`.

1. Atomic publishes can happen via database transactions, which was not an option when we were doing course imports into MongoDB.
2. We can still reconstruct snapshot-in-time from the ItemVersion creation dates and/or some explicit publish log (something has to keep track of what's actually published, since not all versions would be).
3. A saner data model would allow us to do much more granular caching at the ItemVersion/ComponentVersion level, removing the need to do it at the level of the entire LearningContext.

**Comment by feanil** [comment]
> We can still reconstruct snapshot-in-time from the ItemVersion creation dates and/or some explicit publish log (something has to keep track of what's actually published, since not all versions would be).

Won't the publish log essentially be LearningContextVersionItemVersion, or do you think we would map to a higher level component like LearningContextVersionUnitVersion and then figuring out which items are in a specific LC would be slightly more expensive to figure out but not impossible.

**Comment by ormsbee** [comment]
I was thinking that:

1. There's a model that keeps track of the currently published versions. This is size N, where N is the number of items in the context as a whole, and doesn't grow with the number of versions.
2. There can be a model that tracks "this was published at this time" on a per-ItemVersion basis. That does grow with the number of versions V.

So the space usage in that scenario is N + V. But since we don't need to re-write every item for every version, it's no longer N*V. Does that make sense?

**Comment by ormsbee** [comment]
Another random thought: this model might be necessary just to enforce the constraint that there's only one version of a component/item per learning context. 😞

**Comment by feanil** [comment]
> There's a model that keeps track of the currently published versions. This is size N, where N is the number of items in the context as a whole, and doesn't grow with the number of versions.

So in this model, we would both add and delete rows as it made sense to represent only the current items in the learning context?

**Comment by bradenmacdonald** [comment]
> a library with thousands of things in it will get thousands of rows updated for a single published change, because only a handful of Items may change from version to version

For what it's worth: I'm not convinced there's even any value in being able to version a content library as a whole. For the library use case at least, I suspect that being able to edit each individual component as a draft and then publish individually would be totally sufficient. (In fact, I would guess that even that limited per-item draft-publish workflow is unlikely to be heavily used in the sense of people making multiple changes per draft before publishing. I suspect 90%+ of the time, people will just make a change and publish the new item immediately. Unless the UX includes a really convenient "preview, iterate, publish" workflow to guide you to review your changes before publishing, in which case people may do [edit draft, preview, revise draft, preview, publish].)

For courses and other course-like contexts as well, I don't think there's a need for fine-grained tracking of every "version" of the course, where each edit is a version. We just need the "current version used in the draft" for each Item (which would be sufficient to "enforce the constraint that there's only one version of a component/item per learning context."), and the ability to trigger the creation of snapshots at points in time, for publishing to learners, for backups (e.g. daily snapshot) and for authoring convenience ("reset to manually saved snapshot from 10min ago").

Creating a "version" of the course for each edit creates a ton of noise in the data, and is mostly useful if you want to implement an undo button, but undo buttons at that level are very complicated, when pressing undo could revert a recent change made by some other author deep within the course, and you'd have no good sense of what just changed when you clicked "undo".

**Comment by Lyla-Fischer** [comment]
>For courses and other course-like contexts as well, I don't think there's a need for fine-grained tracking of every "version" of the course, where each edit is a version.

I agree. If you think about a git-like workflow, course authors should be able to put together a single commit with all of the interdependent changes published together. This will be especially relevant if authoring/publishing teams ever become separate from teaching teams. The publishers will want to update training and certification with each significant update, and rolling out super-granular changes can be really disorienting to teachers who are focused more on student progress than course content.

**Comment by ormsbee** [comment]
Closing this issue–the model was removed.
