### ISSUE TITLE
Refactoring Proposal: Rename `Content` model to `RawContent`

### ISSUE THREAD

**Issue by ormsbee** [openedx/openedx-learning#32]
I've come to appreciate that I use the word "Content" all the time in a very general sense, and I don't want to cause confusion about whether I'm talking about a general concept or a specific low level model. `RawContent` has a more accurate connotation of what it is (pretty much bytes with only the barest MIME type metadata). And it makes join tables not too awkward–`ComponentVersionRawContent` is understandable, for instance.

**Comment by ormsbee** [comment]
FYI @bradenmacdonald, @kdmccormick, @feanil

**Comment by kdmccormick** [comment]
I like it 👍🏻

**Comment by bradenmacdonald** [comment]
Seems reasonable to me.

**Comment by feanil** [comment]
Makes sense to me as well.  👍🏾

**Comment by ormsbee** [comment]
Accepted and closing, as I'm doing this work as part of https://github.com/openedx/openedx-learning/pull/33
