### ISSUE TITLE
Store v2 library content with `components` and `publisher` models

### ISSUE THREAD

**Issue by ormsbee** [openedx/openedx-learning#44]
Now that these models are mostly baked, start a branch that will store existing v2 library content. This would include:

* updating this repo to accommodate any additional required data models and APIs
* creating a branch in edx-platform that will optionally load data in via management command

To limit scope, this would only be one time import (so no need to create feature flags). Follow-on stories would actually enable read-write capability on a Course-waffle-toggled basis.

This would be to enable tagging to build on the data models in this repo.

**Comment by bradenmacdonald** [comment]
@ormsbee I don't think this ticket is actually "in progress" right?
As you saw in my email to Jenna though I would like to start working soon on a plan for using learning core for libraries, at least at a high level.
