### ISSUE TITLE
Unified `openedx` namespace with edx-platform?

### ISSUE THREAD

**Issue by ormsbee** [openedx/openedx-learning#9]
@jmbowman writes:

> Instead of using `openedx_learning` as the top-level module, could we turn edx-platform's `openedx` into a namespace package so we could use `openedx.learning` instead? 
> 
> https://packaging.python.org/en/latest/guides/packaging-namespace-packages/
>
> Feels like that would also make it much easier to move submodules around between repos.

**Comment by ormsbee** [comment]
I'm capturing this here so I don't forget, and so others can chime in. The rest of our Slack conversation:

> @ormsbee: While I did think about the whole `openedx_learning` vs. `openedx.learning` thing early on, I thought it would be more confusing in the long run. `openedx_learning` is clunkier, but it’s clear where it’s coming from. And I feel like the refactoring aspect is less important since most imports will break loudly and renaming them is not as big a deal. Though I’m not really up to speed on what moving models is like.
>
> I was also worried about coming across weird conflicts, like having an `openedx.learning.student` pop up on both sides or something.
>
> I’ve never made two repos with a shared namespace before though, so a lot of this is lack of experience of what the issues and benefits are.
> 
>  @jmbowman: The tl;dr as I understand it is "just delete `__init__.py`".  There are some corner cases where things work a little differently as a result, but hitting them seems pretty rare.

**Comment by Ian2012** [comment]
Can this one be closed?

**Comment by ormsbee** [comment]
Yeah. If someone wants to really champion this and push it forward, we can re-open. But it doesn't seem worth the effort to me, and I don't see us getting around to working on this.
